# Конфигурация DynamicEventsMC
# Время в минутах между спавном сундуков
spawn-interval: 30

# Настройки сундуков
chest-settings:
  # Время до открытия в секундах
  open-time: 600
  # Расстояние PvP зоны в блоках
  pvp-zone-radius: 250
  # Расстояние видимости босс-бара
  bossbar-radius: 500

# Настройки миров
worlds:
  # Миры где могут спавниться сундуки
  enabled-worlds:
    - "world"          # Верхний мир
    - "world_nether"   # Нижний мир
    - "world_the_end"  # Энд

  # Настройки спавна по мирам
  spawn-settings:
    world:
      min-x: -1000
      max-x: 1000
      min-z: -1000
      max-z: 1000
      min-y: 60
      max-y: 120
    world_nether:
      min-x: -500
      max-x: 500
      min-z: -500
      max-z: 500
      min-y: 32
      max-y: 120
    world_the_end:
      min-x: -500
      max-x: 500
      min-z: -500
      max-z: 500
      min-y: 50
      max-y: 80

# Шансы появления сундуков по редкости
rarity-chances:
  LEGENDARY: 0.05  # 5%
  EPIC: 0.15       # 15% (0.2 - 0.05)
  RARE: 0.30       # 30% (0.5 - 0.2)
  COMMON: 0.50     # 50% (остальное)

# Лут для сундуков
loot:
  COMMON:
    bread:
      material: "BREAD"
      amount: "4...8"
      chance: 0.95
      display-name: "§fХлеб"
      lore:
        - "§7Простая еда"

    apple:
      material: "APPLE"
      amount: "3...6"
      chance: 0.9
      display-name: "§cЯблоко"

    cobblestone_stack:
      material: "COBBLESTONE"
      amount: "32...64"
      chance: 0.85
      display-name: "§7Булыжник"

    oak_planks:
      material: "OAK_PLANKS"
      amount: "20...40"
      chance: 0.85
      display-name: "§6Доски"

    torch_pack:
      material: "TORCH"
      amount: "10...20"
      chance: 0.9
      display-name: "§eФакелы"

    dirt_stack:
      material: "DIRT"
      amount: "32...64"
      chance: 0.8
      display-name: "§7Земля"

    wheat_seeds:
      material: "WHEAT_SEEDS"
      amount: "5...10"
      chance: 0.7
      display-name: "§aСемена пшеницы"

    carrot:
      material: "CARROT"
      amount: "2...5"
      chance: 0.7
      display-name: "§eМорковь"

    cooked_porkchop:
      material: "COOKED_PORKCHOP"
      amount: "3...6"
      chance: 0.8
      display-name: "§6Жареная свинина"

    stick:
      material: "STICK"
      amount: "4...8"
      chance: 0.9
      display-name: "§7Палки"

  RARE:
    iron_sword:
      material: "IRON_SWORD"
      amount: "1"
      chance: 0.8
      display-name: "§fЖелезный меч"
      enchants:
        DAMAGE_ALL: 3
        DURABILITY: 2

    iron_chestplate:
      material: "IRON_CHESTPLATE"
      amount: "1"
      chance: 0.8
      display-name: "§fЖелезный нагрудник"
      enchants:
        PROTECTION_ENVIRONMENTAL: 3
        DURABILITY: 2

    bow:
      material: "BOW"
      amount: "1"
      chance: 0.8
      display-name: "§aОхотничий лук"
      enchants:
        ARROW_DAMAGE: 2
        DURABILITY: 1

    cooked_beef:
      material: "COOKED_BEEF"
      amount: "4...8"
      chance: 0.8
      display-name: "§6Стейк"

    golden_apple:
      material: "GOLDEN_APPLE"
      amount: "1"
      chance: 0.8
      display-name: "§6Золотое яблоко"

    iron_pickaxe:
      material: "IRON_PICKAXE"
      amount: "1"
      chance: 0.8
      display-name: "§7Железная кирка"
      enchants:
        DIG_SPEED: 2

    shield:
      material: "SHIELD"
      amount: "1"
      chance: 0.8
      display-name: "§fЩит"
      enchants:
        DURABILITY: 2

    book_protection:
      material: "ENCHANTED_BOOK"
      amount: "1"
      chance: 0.8
      display-name: "§bКнига защиты"
      enchants:
        PROTECTION_ENVIRONMENTAL: 4

    arrow_stack:
      material: "ARROW"
      amount: "16...32"
      chance: 0.8
      display-name: "§fСтрелы"

  EPIC:
    diamond_helmet:
      material: "DIAMOND_HELMET"
      amount: "1"
      chance: 0.8
      display-name: "§bАлмазный шлем"
      enchants:
        PROTECTION_ENVIRONMENTAL: 4
        DURABILITY: 3

    crossbow:
      material: "CROSSBOW"
      amount: "1"
      chance: 0.8
      display-name: "§5Арбалет"
      enchants:
        QUICK_CHARGE: 2
        MULTISHOT: 1

    enchanted_golden_apple:
      material: "ENCHANTED_GOLDEN_APPLE"
      amount: "1"
      chance: 0.8
      display-name: "§dЗачарованное яблоко"

    golden_carrot:
      material: "GOLDEN_CARROT"
      amount: "5...10"
      chance: 0.8
      display-name: "§6Золотая морковка"

    ender_pearl:
      material: "ENDER_PEARL"
      amount: "1...3"
      chance: 0.8
      display-name: "§dЖемчуг Эндера"

    diamond_sword:
      material: "DIAMOND_SWORD"
      amount: "1"
      chance: 0.8
      display-name: "§bАлмазный меч"
      enchants:
        DAMAGE_ALL: 6
        FIRE_ASPECT: 1
        DURABILITY: 3

    diamond_chestplate:
      material: "DIAMOND_CHESTPLATE"
      amount: "1"
      chance: 0.8
      display-name: "§bАлмазная броня"
      enchants:
        PROTECTION_ENVIRONMENTAL: 4
        THORNS: 2
        DURABILITY: 3

    potion_healing:
      material: "POTION"
      amount: "1"
      chance: 0.8
      display-name: "§cЗелье лечения"
      potion-data:
        type: "INSTANT_HEALTH"
        level: 2
        extended: false

    potion_swiftness:
      material: "POTION"
      amount: "1"
      chance: 0.8
      display-name: "§9Зелье скорости"
      potion-data:
        type: "SPEED"
        level: 2
        extended: true

    book_sharpness:
      material: "ENCHANTED_BOOK"
      amount: "1"
      chance: 0.8
      display-name: "§bКнига остроты"
      enchants:
        DAMAGE_ALL: 5

  LEGENDARY:
    god_sword:
      material: "NETHERITE_SWORD"
      amount: "1"
      chance: 0.8
      display-name: "§6☠ Меч Бога"
      custom-model-data: 1001
      lore:
        - "§7Легендарное оружие"
        - "§cНикто не устоит"

      enchants:
        DAMAGE_ALL: 10
        FIRE_ASPECT: 2
        DURABILITY: 5

    netherite_chestplate:
      material: "NETHERITE_CHESTPLATE"
      amount: "1"
      chance: 0.8
      display-name: "§6Броня Бога"
      enchants:
        PROTECTION_ENVIRONMENTAL: 5
        THORNS: 3
        DURABILITY: 5

    totem_of_undying:
      material: "TOTEM_OF_UNDYING"
      amount: "1"
      chance: 0.8
      display-name: "§eТотем Бессмертия"

    elytra:
      material: "ELYTRA"
      amount: "1"
      chance: 0.8
      display-name: "§bКрылья дракона"
      enchants:
        DURABILITY: 3

    enchanted_golden_apple:
      material: "ENCHANTED_GOLDEN_APPLE"
      amount: "1"
      chance: 0.8
      display-name: "§dЗачарованное яблоко"

    potion_strength:
      material: "POTION"
      amount: "1"
      chance: 0.8
      display-name: "§4Зелье силы"
      potion-data:
        type: "STRENGTH"
        level: 2
        extended: false

    book_unbreaking:
      material: "ENCHANTED_BOOK"
      amount: "1"
      chance: 0.8
      display-name: "§bКнига прочности"
      enchants:
        DURABILITY: 3

# Сообщения
messages:
  chest-spawned: "§6[DynamicEvents] §e{rarity} сундук появился в мире {world}!"
  chest-opened: "§6[DynamicEvents] §a{rarity} сундук открыт! Торопитесь забрать лут!"
  pvp-zone: "§c⚔ ПВП ЗОНА"
  pve-zone: "§a🛡 ПВЕ ЗОНА"
  pve-kill-log: "§c[PvE Kill] §f{killer} §cубил §f{victim} §cв PvE зоне!"

# Настройки эффектов
effects:
  # Частота эффектов в тиках (20 тиков = 1 секунда)
  particle-interval: 40
  sound-interval: 40

  # Интенсивность эффектов
  particles:
    enchantment-table: 20
    rarity-particles: 10
    explosion-on-open: 5

  # Громкость звуков
  sounds:
    ambient-volume: 0.3
    open-volume: 1.0

# Дебаг режим
debug:
  enabled: false
  log-chest-spawn: true
  log-player-zones: false